### ISSUE TITLE
Is the license for this library MIT?

### ISSUE THREAD

**Issue by triacontane** [sbfkcel/pixi-apngAndGif#1]
Greetings.
Thank you for the wonderful library.

"LICENSE.txt" was not found in the project, but "package.json" was written MIT.

Is there a license for this library at MIT?
I apologize for any rudeness because I used machine translation.

**Comment by sbfkcel** [comment]
You can use it freely

**Comment by triacontane** [comment]
Thank you for your answer.
It was very helpful.
