### ISSUE TITLE
get individual frame for reuse?

### ISSUE THREAD

**Issue by thewayur** [sbfkcel/pixi-apngAndGif#4]
can we get individual frame as data/buffer so that we can reuse it in javascript/dom?

e.g. i want to split all the frames of apng and show it as list in divs/imgs.
so that user can pick frame manually.

thanks for great library

**Comment by sbfkcel** [comment]
Of course, the easiest way. Convert frame data to base64

```
var base64Img = canvas.toDataURL('image/png');
```

```
<img src="data:image/png;base64,{base64Img}"/>
```

**Comment by thewayur** [comment]
> Of course, the easiest way. Convert frame data to base64
> 
> ```
> var base64Img = canvas.toDataURL('image/png');
> ```
> 
> ```
> <img src="data:image/png;base64,{base64Img}"/>
> ```
no, i want the data of supplied apng/gif only, 
not for the whole canvas

e.g. if my APNG has 8 frames, and i am supplying 2 APNGs,
i want their's individual data frames.
is it possible or any workaround by changing code?

possible method =
let img1Frames[2] = apng.getFrames().frame[2].dataUrl;

**Comment by sbfkcel** [comment]
Jump to the specified frame through `jumpToFrame`, get the picture data of the frame, and display it on the dom. There is no problem.


```
var getFrameBase64= frame => {
  apng.jumpToFrame(1);
  return canvas.toDataURL('image/png');
}
var img1Base64 = getFrameBase64(1);
var img2Base64 = getFrameBase64(2);

img1.src = `data:image/png:base64,${img1Base64 }`;
img2.src = `data:image/png:base64,${img2Base64 }`;
```

**Comment by thewayur** [comment]
` return canvas.toDataURL('image/png');`

@sbfkcel so, i have to render gif/png on canvas first? like in separate solo canvas?

**Comment by sbfkcel** [comment]
It can also be more direct, and you may need to modify the method yourself.

Refer to the parsed APNG data method:
https://github.com/sbfkcel/pixi-apngAndGif/blob/master/src/PixiApngAndGif.es6#L262

**Comment by thewayur** [comment]
finally  i did it :D 

on line [301](https://github.com/sbfkcel/pixi-apngAndGif/blob/master/src/PixiApngAndGif.es6#L301) and [353](https://github.com/sbfkcel/pixi-apngAndGif/blob/master/src/PixiApngAndGif.es6#L353)
just add this

`console.log(`pngFrame${i}`, canvas.toDataURL('image/png'));`

and it will log individual frame data as base64 uri, e.g.
![image](https://user-images.githubusercontent.com/2944767/126711691-2c678092-4fe1-4254-be83-eacf43458466.png)


later u can return them with obj (line 306, 358)

and u can use it in dom as =

`let img1 = document.getElementById('img1');`
`img1.src = pngFrames[0];`


thanks @sbfkcel for helping us! respect

**Comment by thewayur** [comment]
> Jump to the specified frame through `jumpToFrame`, get the picture data of the frame, and display it on the dom. There is no problem.
> 
> ```
> var getFrameBase64= frame => {
>   apng.jumpToFrame(1);
>   return canvas.toDataURL('image/png');
> }
> var img1Base64 = getFrameBase64(1);
> var img2Base64 = getFrameBase64(2);
> 
> img1.src = `data:image/png:base64,${img1Base64 }`;
> img2.src = `data:image/png:base64,${img2Base64 }`;
> ```

**corrections need, 
first:**
`return canvas.toDataURL('image/png');`
it will return data with string = `data:image/png;base64,` , so we dont need to prefix anything. Just pass returned string directly to img source

**second:**
there should be SEMICOLON instead COLON in between **png** and **base64**:
i.e.
ur code:
`data:image/png:base64,`

correct code:
`data:image/png;base64,`

**third (most imp)**
the above method will return blank black base64, it is because we r not returning the PIXIs render view.. i.e. we have to add sprite to render view.. (i had encountered and troubleshooted this months ago, and kinda forgot actual issue :D)
