### ISSUE TITLE
simple implementation in own js

### ISSUE THREAD

**Issue by thewayur** [sbfkcel/pixi-apngAndGif#5]
Hi again, your code, demo is working fine. :), but when i tried to implement it in my own js file. i got errors. 
may be i am doing it wrong way. please help me 

`<script src="pixi.min.5.1.3.js"></script>`
`<script src="PixiApngAndGif.js"></script>`
`<script src="my.js"></script>`

in **my.js**
`
var gifUrl = '1.gif';
var apngUrl = '1.png';
var texture = '';

var app = new PIXI.Application({
    view: document.getElementById('canvas')
});

 
 
let loader = new PIXI.Loader();

loader.add(gifUrl);
loader.onComplete.add(handleLoadComplete);
loader.load();

function handleLoadComplete() {

    texture = loader.resources[gifUrl].texture;
    createCanvas();
} 

function createCanvas() {

    apngSprite = new PIXI.Sprite(texture);
    app.stage.addChild(apngSprite);
};

`

above code is   simple pixijs canvas,
**now how to implement ur library?**

see, when i tried to load it this way:

`var gifSprite = new PixiApngAndGif(gifUrl, loader.resources);`

i got error:
![image](https://user-images.githubusercontent.com/2944767/126632935-f509d5fa-513e-468a-9023-2c04c889f610.png)

and when i try to load with APNG, error:
`var pngSprite = new PixiApngAndGif(pngUrl, loader.resources);`
![image](https://user-images.githubusercontent.com/2944767/126633107-ae432448-98cf-4b7f-8cbb-4be23c1f8aaa.png)

so please guide  
[my.js.zip](https://github.com/sbfkcel/pixi-apngAndGif/files/6861910/my.js.zip)

**also could you please mention/update the code for PIXIJS 5.3.10?**

**Comment by sbfkcel** [comment]
File is not a valid GIF/apng error

**Comment by thewayur** [comment]
> File is not a valid GIF/apng error
 i am using the same files u provided it in this repo,
 and all my imgs are working in ur demo.

please correct this little code: https://codepen.io/thewayur/pen/BaRwMOM
(line no 27 and 28, open browser console to see detailed error, screenshot below ) 
![image](https://user-images.githubusercontent.com/2944767/126689178-be1b05ac-f503-48e9-b7c2-f10ade882390.png)


but in above code it doesnt.

am i using it wrong way?

**Comment by sbfkcel** [comment]
Loader needs to specify options

```javascript
const option  = {
  loadType: PIXI.LoaderResource.LOAD_TYPE.XHR,
  xhrType: PIXI.LoaderResource.XHR_RESPONSE_TYPE.BUFFER,
  crossOrigin:''
},

loader = new PIXI.Loader();
loader.add("gifUrl",option);
loader.add("apngUrl",option);
```

**Comment by thewayur** [comment]
i knew it, i have to place it and i was placing in app's args :p

finally everything working as expected,
thanks a lot man, love from India <3
